BUFFER = 1024
SOCKET_PORTA = 9876
SOCKET_ENDERECO = "localhost"

BANCO_DE_DADOS_ENDERECO = "localhost"
BANCO_DE_DADOS_NOME = "aps5sem"
BANCO_DE_DADOS_USUARIO = "aps"
BANCO_DE_DADOS_SENHA = "aps"

COR_DE_FUNDO_PADRAO = "#FFFFFF"
LOGO_CAMINHO = "imagens/logo.pbm"

FAMILIA_FONTE_PADRAO = "Verdana"
FONTE_LABEL_LOGIN = (FAMILIA_FONTE_PADRAO, 15, "bold")
FONTE_ENTRY_LOGIN = (FAMILIA_FONTE_PADRAO, 20)
FONTE_BTN_LOGIN = (FAMILIA_FONTE_PADRAO, 15, "bold")
FONTE_BTN_MENU = (FAMILIA_FONTE_PADRAO, 20, "bold")
