BUFFER = 4096
SOCKET_PORTA = 9876
SOCKET_ENDERECO = "localhost"

BANCO_DE_DADOS_ENDERECO = "25.104.62.199"
BANCO_DE_DADOS_NOME = "aps"
BANCO_DE_DADOS_USUARIO = "aps"
BANCO_DE_DADOS_SENHA = "aps"

COR_DE_FUNDO_PADRAO = "#FFFFFF"
COR_DE_FUNDO_BTN_LISTA = "#808080"
LOGO_CAMINHO = "imagens/logo.pbm"

FAMILIA_FONTE_PADRAO = "Verdana"
FONTE_LABEL_LOGIN = (FAMILIA_FONTE_PADRAO, 15, "bold")
FONTE_ENTRY_LOGIN = (FAMILIA_FONTE_PADRAO, 20)
FONTE_BTN_LOGIN = (FAMILIA_FONTE_PADRAO, 15, "bold")
FONTE_LABEL_CADASTRO = (FAMILIA_FONTE_PADRAO, 15, "bold")
FONTE_ENTRY_CADASTRO = (FAMILIA_FONTE_PADRAO, 20)
FONTE_BTN_CADASTRO = (FAMILIA_FONTE_PADRAO, 15, "bold")
FONTE_BTN_MENU = (FAMILIA_FONTE_PADRAO, 20, "bold")
FONTE_INFO_USUARIOS = (FAMILIA_FONTE_PADRAO, 15, "bold")
FONTE_BTN_USUARIOS = (FAMILIA_FONTE_PADRAO, 10)
FONTE_INFO_GRUPOS = (FAMILIA_FONTE_PADRAO, 15, "bold")
FONTE_BTN_GRUPOS = (FAMILIA_FONTE_PADRAO, 10)
FONTE_CHAT_MENSAGEM_RECEBIDA = (FAMILIA_FONTE_PADRAO, 15)
FONTE_CHAT_MENSAGEM_ENVIADA = (FAMILIA_FONTE_PADRAO, 15)
FONTE_CHAT_BTN_ENVIAR = (FAMILIA_FONTE_PADRAO, 20, "bold")
FONTE_CHAT_BTN_SAIR = (FAMILIA_FONTE_PADRAO, 15, "bold")

