TAMANHO_BUFFER = 1024
SOCKET_PORTA = 9876
SOCKET_ENDERECO = "localhost"

BANCO_DE_DADOS_ENDERECO = "localhost"
BANCO_DE_DADOS_NOME = "aps5sem"
BANCO_DE_DADOS_USUARIO = "aps"
BANCO_DE_DADOS_SENHA = "aps"

COR_DE_FUNDO_PADRAO = "#FFFFFF"
LOGO_TELA_DE_LOGIN = "imagens/logo.pbm"

FAMILIA_FONTE_PADRAO = "Verdana"
LOGIN_FONTE_LABEL = (FAMILIA_FONTE_PADRAO, 15, "bold")
LOGIN_FONTE_ENTRY = (FAMILIA_FONTE_PADRAO, 20)
LOGIN_FONTE_BTN = (FAMILIA_FONTE_PADRAO, 15, "bold")
